[calamities]
title = "calamities (by Shializaro)"
url = "https://archiveofourown.org/works/30589355/navigate"
entrySelector = "#main > ol > li"
titleSelector = "a"
linkSelector = "a"
dateSelector = "span"
dateFormat = "(yyyy-MM-dd)"

